### ISSUE TITLE
How to create .bin file in ./grid_sensor/data_kitti/superpixel_bin/?

### ISSUE THREAD

**Issue by HyuanTan** [shichaoy/semantic_3d_mapping#1]
Hi, thanks for share!
I was confused that what the data struct in ./grid_sensor/data_kitti/superpixel_bin/000000.bin and how to create these files?
Thanks!

**Comment by shichaoy** [comment]
Hi, we upload more instructions for data preparation. See folder /preprocess_data. For superpixel, we upload full code which you can directly use.

**Comment by HyuanTan** [comment]
@shichaoy Thanks for your help! The folder /preprocess_data do me great favor.

**Comment by sqfsummer18** [comment]
Hi @shichaoy , I tried running superpixel_img2bin.m in matlab with your original directory and files. But it raise error as follow:

Index in position 1 exceeds array bounds (must not exceed 170).

Error in superpixel_img2bin(line 31)
              next_ind =sp_mat(c, 1) + 1;

do you have some suggestions on that?

**Comment by shichaoy** [comment]
@sqfsummer18  I re-run the code in my and other computer and don't meet problems. That line means you have more superpixels than 170, exceeding the matrix rows. I add a check max(max(im)) in the code. Let me know if you still have problems.
