### ISSUE TITLE
How to get the camera position and CameraTrajectory.txt

### ISSUE THREAD

**Issue by anzisheng** [shichaoy/semantic_3d_mapping#12]
First, thank you for sharing the code?
Could you tell me how to get the "CameraTrajectory.txt"? and meaning  of parameters of each row.
And I want to know how to compute the camera pos？
                            Thanks!

**Comment by shichaoy** [comment]
hi, @anzisheng  that is output from orbslam. Each row representing a camera pose.  each row 12 numbers, which are the flattened number of top 3 rows of standard 4*4 pose matrix.  namely each row is flattened [R t]
