### ISSUE TITLE
 evaluatioList.txt

### ISSUE THREAD

**Issue by qq664956261** [shichaoy/semantic_3d_mapping#15]
Hi, thanks for share!
how can i get the  evaluatioList.txt
i can run without the evaluatioList.txt
what is the function of it
@shichaoy

**Comment by shichaoy** [comment]
@qq664956261  sorry for the late reply. Evaluationlist.txt is the image index where there is ground truth semantic segmentation. For image index in the list.txt, we project the map data onto image, then compare with ground truth. You can ignore it if you don't want.

**Comment by qq664956261** [comment]
thank you very much, very useful, and also thanks your sharing code.

**Comment by zeroAska** [comment]
@shichaoy Where are the ground truth labels? Is it in data_kitti/?

**Comment by shichaoy** [comment]
@zeroAska  I uploaded a folder ```preprocess_data/gt_label/``` containing the processed ground truth images used in our paper.
