### ISSUE TITLE
How to save the final semantic map?

### ISSUE THREAD

**Issue by HyuanTan** [shichaoy/semantic_3d_mapping#2]
Hi, thanks for share!
Could you please tell me how to save the final semantic map like this?
![screenshot from 2018-06-05 15-08-10](https://user-images.githubusercontent.com/14145396/40960620-e5d6cd50-68d2-11e8-8593-57f7a5d7c619.png)

Thanks!!

**Comment by HyuanTan** [comment]
Hi, thanks for share!
I find the way to save the final semantic map in paper:
![screenshot from 2018-06-12 14-02-44](https://user-images.githubusercontent.com/14145396/41284466-ef817afa-6e6b-11e8-8a64-01f52476e304.png)

and set `gridDimensionX/gridDimensionY` in lauch file to special value.

Thanks!!

**Comment by shichaoy** [comment]
Hi, sorry for the late reply. I get the screenshot just through Rviz, but setting the pointcloud decay time to a large number, say 1e5.       You can also save them in code: write all the local pointcloud into one giant pointcloud, (this is easy as they are already in global coordinates), then save this pointcloud into a PCD file. I didn't write code for this part yet.

**Comment by HyuanTan** [comment]
Hi, thanks for reply and I will try your suggestions.

**Comment by qq664956261** [comment]
Could you please send me the author's dataset? The download link failed. Thank you. @HyuanTan
