### ISSUE TITLE
404 Not Found when download data

### ISSUE THREAD

**Issue by chubahien** [shichaoy/semantic_3d_mapping#6]
Thank you for sharing your code. 

I can not download data_kitti.zip at http://www.frc.ri.cmu.edu/~syang/dataset/kitti_crf/data_kitti.zip
Could you give another link to download this data_kitti.zip?

**Comment by shichaoy** [comment]
Hi, Thanks for the interest. I think it is due to recent server changes. I put it temporarily here. Refer to sh file to put it in right place. https://drive.google.com/open?id=1cfQYQMkU1cZn6e4hPsgGyYwvKfh7gYV7

I will update the sh file when I find a stable position.

**Comment by chubahien** [comment]
@shichaoy Thank you for the download link.
