### ISSUE TITLE
can not read depth image

### ISSUE THREAD

**Issue by YiheChen1995** [shichaoy/semantic_3d_mapping#7]
Hello! I have realized that there are only 20 depth images in your data set. And it complains about can not read depth image when the index goes to 20

**Comment by shichaoy** [comment]
Hi, there is only 20 images for depth, labels, rbgs due to the large data size of them. I didn't put the whole dataset online.  If you want to run more examples, you can follow ```preprocess_data/``` to build on your own.

**Comment by YiheChen1995** [comment]
okay Thanks!
